### ISSUE TITLE
config.yml to reproduce the experiments in the paper

### ISSUE THREAD

**Issue by Hayashi-Yudai** [Asa9aoTK/ANS-Recbole#2]
I heard your excellent presentation at RecSys the other day and would like to try to reproduce the ANS experiment on my own.

As a start, I have been trying to reproduce the results presented in the paper using the Gowalla dataset used in the paper, but have not been successful. If you don't mind, could you please tell me what config.yml you use for your experiments during training?

I am trying a LightGCN based implementation and am using a config.yml like this

```yml
epochs: 100
stopping_step: 100
embedding_size: 64
n_layers: 3
eps: 0.1
gamma: 0.1
reg_weight: 0.0001
require_pow: False

load_col:
    inter: [user_id, item_id]
eval_args:
  group_by: user
  split: {'RS': [0.8,0.1,0.1]}
  mode: full

learner: adam
learning_rate: 0.001
train_batch_size: 2048
valid_batch_size: 2048
eval_batch_size: 2048
train_neg_sample_args:
  candidate_num: 32
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 20
valid_metric: Recall@20
```

<details>
<summary>reference information</summary>

Recall@20

red line: LightGCN
blue line: LightGCN w/ ANS

<img width="998" alt="image" src="https://github.com/Asa9aoTK/ANS-Recbole/assets/34836226/acc768f0-23eb-44e7-8e41-abd25335b56a">

</details>
